In [2]:
#importing necessary packages
import numpy as np
import pandas as pd

In [19]:
data=pd.read_csv("/content/insurance.csv")

In [20]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [21]:
data.info() #basic idea that we get from the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [22]:
data.describe()#statistical analysis

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
#data preprocessing
#convert categorical variables into numerical variables using one hot encoding technique

In [23]:
data['smoker']=data['smoker'].apply({'yes':1,'no':0}.get)

In [24]:
data.head()

   age     sex     bmi  children  smoker     region      charges
0   19  female  27.900         0       1  southwest  16884.92400
1   18    male  33.770         1       0  southeast   1725.55230
2   28    male  33.000         3       0  southeast   4449.46200
3   33    male  22.705         0       0  northwest  21984.47061
4   32    male  28.880         0       0  northwest   3866.85520

In [25]:
data['sex']=data['sex'].apply({'female':0,'male':1}.get)

In [26]:
data.head()

   age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [27]:
data['region']=data['region'].apply({'southeast':0,'northeast':2,'northwest':3,'southwest':1}.get)

In [28]:
data.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       0   1725.55230
2   28    1  33.000         3       0       0   4449.46200
3   33    1  22.705         0       0       3  21984.47061
4   32    1  28.880         0       0       3   3866.85520

In [ ]:
#third step in machine learning is dividing the data
#dividing the data in dependent and independent columns

In [29]:
X=data[['age','sex','bmi','children','smoker','region']]#independent features from the dataset

y=data['charges'] #dependent column from the dataset

In [31]:
X.head()

   age  sex     bmi  children  smoker  region
0   19    0  27.900         0       1       1
1   18    1  33.770         1       0       0
2   28    1  33.000         3       0       0
3   33    1  22.705         0       0       3
4   32    1  28.880         0       0       3

In [32]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [35]:
# 4 th step of machine learning  to splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)#20%of the dataset will be used for testing(evaluation)
#80% of the data is to be used for training purposes

In [36]:
#create the machine learning model
from sklearn.linear_model import LinearRegression
linearmodel=LinearRegression()
linearmodel.fit(X_train,y_train) # training is taking place

LinearRegression()

In [37]:
#predictions
linearmodel.predict(X_test)

array([14102.31992125,   -90.39833711, 11719.99645974,  7784.69863469,
       27679.45692734, 33761.8560374 , 13186.74987095, 34147.88121202,
       10743.52629394, 12254.10724903,  8491.83210199,  6995.72854239,
       12537.98369528, 10880.0393148 , 12294.19454644, 15736.20207265,
        9566.72736992,  8389.51541056, 26962.31811994,  3297.76666176,
        3056.15958217, 36447.76166104,  7391.88567462, 10870.83438256,
        2434.09041296, 15112.74263205, 34374.1241981 , 32343.95677833,
       30062.00143144,  4716.38550149,  8131.38229279, 28385.61729095,
       31227.2343207 ,  1670.79777449, 10229.01730111,  9784.36951436,
       11001.83005148, 31301.20481474,  1793.07575743, 33294.3547083 ,
       29935.14571077,  9028.42850721, 37035.30166349, 12375.90905591,
       35730.28588394, 13627.74908809,  2122.01432215,  9638.16112932,
       11162.18734761,  6606.17722604, 29363.27939793, 13069.36619424,
       30971.20749457,  1336.59216673,  9263.80770635,  3867.67424482,
       16492.28458304, 13961.40112829,  3319.58386791, 10207.22365304,
       13349.05847784, 14488.86466435,  2129.33958889, 32202.87064641,
        5433.6893702 ,  5242.722     , 23008.23770281,  6832.82448843,
       10448.39757492,  8844.85960564, -1331.29455379, 13053.44509746,
        1989.49847768, 10306.29118861, 37824.79157429,   855.91024023,
        7172.17458153,  2294.29509204,  9180.58635998,  9039.74849522,
       12046.91139104,  5026.52755941,   206.41915548, 36806.5757762 ,
       19191.74982111, 33644.90362567, 38083.97773415, 40382.60853579,
       11282.97404149,  9658.33529495, 13550.51212576,  7076.76967933,
        8946.08234648,  8920.67071651, 15626.29908062,  9396.86850838,
       16111.3696884 , 14981.68019968,  7458.94094372,  9472.56148705,
       29831.36901466, 34624.42603478, 14661.2915449 ,  4159.99882945,
       12595.53234939, 16635.26832208, 11681.81683064,  7114.20068304,
       11276.63761497, 33427.51494702,  9543.64105613,  4579.8974848 ,
        6637.9173692 ,  5712.72029406,  4544.14260856, 17149.35149857,
       39781.96876313,  9290.92566659, 16864.70391588, 11620.80365177,
        4538.81444286, 10845.77922056, 10711.18950765,  4405.54943904,
         939.26779022, 11698.89674364, 13317.33048647, 32091.05727137,
        4440.98592662,  1019.6491433 ,  2194.46205573,  6347.0182182 ,
       40990.2011552 , 15145.04851379, 12856.66831668,  9126.774108  ,
        4603.56922249, 10311.07755362,  3260.41345371, 14058.24638786,
       28798.34237378,  8941.10335952,  1968.31762711,  5874.09929068,
       10353.35206167, 12447.79675915, 16116.08215485,  5950.89423017,
       30027.12504676, 27567.46227939, 12239.45144437,  4152.32296633,
       11794.24564533,  2126.93218645,  5789.13291063,  4652.42598834,
       33913.52059448,  6846.07970539, 12812.67084893, 26466.84604498,
        5555.48010688,  3420.51485738, 13514.6216371 , 11023.51234186,
       35139.19021831,  -815.38078366, 29100.65823477, 26876.0347951 ,
       11683.12056657,  8915.91905235, 35792.7299831 , 12985.15973138,
        7825.86332582,  5396.66406046, 26875.02697134,  3780.24846439,
       12408.39911232, 27509.21912134,  3489.63907514, 15038.68143665,
       -1134.50758203, 14666.65821165, 26019.39790482, 11377.87142602,
        3725.56493753, 25216.78220106, 11679.43557118,  9192.88932582,
       31549.69469607, 14381.52495858, 15611.06356542, 15175.13346464,
        3435.57196852,  3221.585298  ,  7174.26365255,  2661.42287199,
       39199.80662744,  5891.1150018 , 10255.29121104, 10214.72931346,
       10218.42165532,  7654.60268052,  9422.08766544,  6435.13128588,
       15479.66759906,  9338.50856323,  7364.67543714, 12220.82183436,
       11081.8210673 ,  9575.18257595, 11527.17437096, 15273.93130359,
       37160.26592745,  2328.37233749, 40275.74343019, 12835.51089438,
       11319.56903803, 25074.66573433,  4771.68046544,  9450.62620594,
        1475.64649676, 16297.10315976,  7746.64692014, 10699.99885184,
       31894.40868397, 13080.51755543, 10138.04802854, 10966.35493304,
        7969.94514782, 11425.87613134,  5805.09992749, 11359.31788165,
       33044.26600087, 32051.56013061,  7128.07304534, 14603.89363322,
       34614.11166545, 24014.45484073, 10820.79182594,  7802.4602565 ,
       10989.88346181,  9018.19982763,  3411.31607555, 11787.00937426,
       10983.54633352,  6736.54730233, 11169.63302419,   827.1925021 ,
        4832.70871708, 33464.30013883,  6117.1760183 ,  5730.52048948,
        9600.30589026,  9832.49692641, 10731.17612015, 11748.68063585,
        6538.44195892, 32767.23344667,  3156.78129238,  4053.28400043,
        5601.23887713, 31519.19323617,  9653.78889884,  3978.75164056,
       17962.3788605 ,  2105.45800862,   809.29382178,  -355.32513115])

In [39]:
#calculating the accuracy of the model
linearmodel.score(X,y) # evaluation is taking polace

0.7500562290778426

In [40]:
#predictions with respect to new dataset
data_new={'age':32,'sex':1,'bmi':25,'children':1,'smoker':0,'region':3}

In [41]:
index=[1]# serial number
my_data=pd.DataFrame(data_new,index)

In [42]:
print(my_data)

   age  sex  bmi  children  smoker  region
1   32    1   25         1       0       3

In [43]:
#charges allocated
my_data_charges=linearmodel.predict(my_data)
print('the charges allocated to the new customer is', my_data_charges)

the charges allocated to the new customer is [4600.25920356]